projeto_integrador/main_site/urls.py
from django.urls import include, path
from main_site.views.login_views import auth, login, logoutAA, register, perform_register
from main_site.views.general_views import home
from main_site.views.projeto_views import excluir_projeto, visualizar_projeto, editar_projeto,performar_editar_projeto, criar_projeto, performar_criar_projeto

app_name='main_site'

urlpatterns = [
    path('', home, name='home'),
    path('login/', login, name='login'),
    path('auth/', auth, name='auth'),
    path('logout/', logoutAA, name='logout'),
    path('register/', register, name='register'),
    path('perform_register/', perform_register, name='perform_register'),
    path('projeto/<int:pk>/', visualizar_projeto, name='visualizar_projeto'),
    path('projeto/editar/<int:pk>/', editar_projeto, name='editar_projeto'),
    path('projeto/editar/performar/<int:pk>/', performar_editar_projeto, name='performar_editar_projeto'),
    path('projeto/criar/', criar_projeto, name='criar_projeto'),
    path('projeto/criar/performar/', performar_criar_projeto, name='criar_projeto_performar'),
    path('projeto/excluir/<int:pk>/', excluir_projeto, name='excluir_performar')
]

projeto_integrador/pi/urls.py
from pi import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_site.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto_integrador/main_site/models.py
from typing import Iterable, Optional
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.files.storage import default_storage
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
import os
import shutil
from pi.settings import MEDIA_ROOT
# Create your models here.

def send(instance, filename):
    return f"images/{filename}"

def sendred(instance, filename):
    return f"images/red-{filename}"
class Projeto(models.Model):
    idprojeto = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=30)
    descricao = models.CharField(max_length=255)
    imagem = models.ImageField(upload_to=send)
    imagem_redimensionada = ImageSpecField(source='imagem', processors=[ResizeToFill(350, 350)], format='JPEG', options={'quality': 60})
    autor = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    
    def save(self, *args, **kwargs) :
        try:
            this = Projeto.objects.get(idprojeto=self.idprojeto)
            if this.imagem != self.imagem:
                if isinstance(this.imagem, InMemoryUploadedFile):
                    # Se a imagem atual for um arquivo em memória, fecha o arquivo antes de excluí-lo
                    this.imagem.file.close()
                try:
                    diretorio = MEDIA_ROOT+'/CACHE/images/images/'
                    conteudo = os.listdir(diretorio)
                    diretorios = [item for item in conteudo if os.path.isdir(os.path.join(diretorio, item))]
                    for diretorioz in diretorios:
                        print(diretorioz)
                        print(os.path.basename(this.imagem.name))
                        if (diretorioz==os.path.basename(this.imagem.name) or diretorioz in os.path.basename(this.imagem.name) or os.path.basename(this.imagem.name) in diretorioz):
                            print("Diretorio excluido")
                            shutil.rmtree(diretorio+diretorioz)
                except:
                    pass
                this.imagem.delete(save=False)
        except Projeto.DoesNotExist:
            pass

        try:
            this = Projeto.objects.get(idprojeto=self.idprojeto)
            if this.imagem_redimensionada != self.imagem_redimensionada:
                if isinstance(this.imagem_redimensionada, InMemoryUploadedFile):
                    this.imagem_redimensionada.file.close()
                this.imagem_redimensionada.delete(save=False)
        except:
            pass
            
        return super(Projeto, self).save(*args, **kwargs)

projeto_integrador/main_site/forms/editor_form.py
from typing import Any, Dict, Mapping, Optional, Type, Union
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from main_site.models import Projeto

class EditorForm(forms.ModelForm):
    class Meta:
        model = Projeto
        fields = ['titulo', 'descricao', 'imagem']

    titulo = forms.CharField(
        label='Nome do projeto',
        widget=forms.TextInput()
        
    )
    titulo.widget.attrs.update(
        {
            "placeholder": "Nome do projeto aqui",
        }
    )
    descricao = forms.CharField(
        label='Descrição do projeto',
        widget=forms.Textarea()
        
    )
    descricao.widget.attrs.update(
        {
            "placeholder": "Descrição do projeto aqui",
            "cols": 30,
            "rows": 10
        }
    )

    imagem = forms.ImageField(
        label ="Capa do projeto",
        widget=forms.ClearableFileInput(),
        required= False
    )
    imagem.widget.attrs.update({
        "placeholder": "Selecione a imagem",
        "required": False
    })

projeto_integrador/main_site/forms/login_form.py
from django import forms
from django.contrib.auth.models import User


def add_attr(field, attr_name, new_attr_val):
    existing_attr = field.widget.attrs.get(attr_name, '')
    field.widget.attrs[attr_name] = f'{existing_attr} {new_attr_val}'.strip()

class LoginForm(forms.Form):
    username = forms.CharField(
         widget=forms.TextInput(attrs={'placeholder': 'Usuário'})
        )
    password = forms.CharField(
        widget=forms.widgets.PasswordInput(attrs={'placeholder': 'Senha'})
        )
    
    

    

projeto_integrador/main_site/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

def add_attr(field, attr_name, new_attr_val):
    existing_attr = field.widget.attrs.get(attr_name, '')
    field.widget.attrs[attr_name] = f'{existing_attr} {new_attr_val}'.strip()

class RegisterForm(forms.Form):

    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Insira o usuário desejado'})
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'placeholder': 'Insira o email desejado'})
    )
    password = forms.CharField(
        widget=forms.widgets.PasswordInput(attrs={'placeholder': 'Insira a senha desejada'})
    )

    def clean_password(self):
        invalid_chars = ['/', '\\', ';', '`', "'", '"', ':']
        string = ''.join(invalid_chars)
        senha = self.cleaned_data['password']
        for char in senha:
            if char in invalid_chars:
                raise ValidationError(f'Você não pode utilizar: {string} na sua senha.', code='invalid')
        return senha

    def clean_email(self):
        email = self.cleaned_data['email']
        exist = User.objects.filter(email=email).first()
        if exist: 
            raise ValidationError(f'Já existe usuário criado com esse email.', code='invalid')
        return email
    
    def clean_username(self):
        username = self.cleaned_data['username']
        exist = User.objects.filter(username=username).first()
        if exist: raise ValidationError(f"Já existe um usuário cadastrado para esse nome de usuário.", code='invalid')
        return username







 # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     add_attr(self.fields['username'], 'placeholder', 'Insira o usuário')
    #     add_attr(self.fields['email'], 'placeholder', 'Insira o email')
    #     add_attr(self.fields['password'], 'placeholder', 'Insira sua senha desejada')
    
        

    # class Meta:
    #     model = User
    #     fields = [
    #         "username", "email", "password"
    #     ]        


    # def clean_email(self):
    #     email = self.cleaned_data['email']
    #     email_exist = User.objects.get(email=email)
    #     if email_exist:
    #         raise ValidationError('Esse e-mail já está sendo usado', code='invalid')

projeto_integrador/main_site/views.py
from django.contrib.staticfiles import finders
from django.shortcuts import render
from main_site.models import Projeto
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as lg
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from main_site.forms.login_form import LoginForm
from django.http import Http404
# Create your views here.

def home(request, *args, **kwargs):
    home_css_path = finders.find('main_site/css/home.css')
    template_path = 'main_site/home.html'
    

    context = {
        "projetos": [
            {"titulo": projeto.titulo, "imagem": "media/"+projeto.imagem.path, "descricao": projeto.descricao[0:len(projeto.descricao)-10]} for projeto in Projeto.objects.all()
        ]
    }
    if request.user.is_authenticated:
        context["usuario_logado"] = request.user.username
    return render(request, template_path, context=context)

def login(request, *args, **kwargs):
    form = LoginForm()
    if (request.user.is_authenticated):
        return redirect(reverse('main_site:home'))
    else:
        return render(request, 'main_site/login.html', {
            'login': True,
            'form': form,
            'form_action': reverse('main_site:auth')
        })
    
def auth(request, *args, **kwargs):
    if not request.POST:
        raise Http404
    form = LoginForm(request.POST)
    if form.is_valid():
        is_authenticated = authenticate(request=request,
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )
        print(is_authenticated)
        if is_authenticated is not None:
            lg(request, is_authenticated)
            print("Está autenticado: ",request.user.is_authenticated)
            return redirect(reverse("main_site:home"))
    return redirect(reverse('main_site:login'))


@login_required(login_url='main_site:login', redirect_field_name='next')
def logoutAA(request):
    logout(request)
    return redirect(reverse('main_site:home'))

projeto_integrador/main_site/views/general_views.py
from django.contrib.staticfiles import finders
from django.shortcuts import render
from main_site.models import Projeto
# Create your views here.

def home(request, *args, **kwargs):
    home_css_path = finders.find('main_site/css/home.css')
    template_path = 'main_site/home.html'
    

    context = {
        "projetos": [
            {"idprojeto": projeto.idprojeto, "titulo": projeto.titulo, "imagem": projeto.imagem_redimensionada.url, "descricao": projeto.descricao[0:20]+'...'} for projeto in Projeto.objects.all()
        ]
    }
    if request.user.is_authenticated:
        context["usuario_logado"] = request.user.username
    return render(request, template_path, context=context)

projeto_integrador/main_site/views/login_views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as lg
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from main_site.forms.login_form import LoginForm
from main_site.forms.register_form import RegisterForm
from django.http import Http404
from django.contrib.auth.models import User

def register(request, *args, **kwargs):
    register_form_data = request.session.get('register_form_data', None)
    form = RegisterForm(register_form_data)

    return render(request, 'main_site/login.html', {
        'login': False,
        'form': form,
        'form_action': reverse('main_site:perform_register')
    })

def perform_register(request, *args, **kwargs):
    if not request.POST:
        raise Http404
    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)
    if form.is_valid():
        user = User(
            username=form.cleaned_data['username'],
            email=form.cleaned_data['email']
        )
        user.set_password(form.cleaned_data['password'])
        user.save()
        del(request.session['register_form_data'])
        return redirect(reverse('main_site:login'))
    return redirect('main_site:register')

def login(request, *args, **kwargs):
    form = LoginForm()
    if (request.user.is_authenticated):
        return redirect(reverse('main_site:home'))
    else:
        return render(request, 'main_site/login.html', {
            'login': True,
            'form': form,
            'form_action': reverse('main_site:auth')
        })
    
def auth(request, *args, **kwargs):
    if not request.POST:
        raise Http404
    form = LoginForm(request.POST)
    if form.is_valid():
        is_authenticated = authenticate(request=request,
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )
        if is_authenticated is not None:
            lg(request, is_authenticated)
            return redirect(reverse("main_site:home"))
    return redirect(reverse('main_site:login'))


@login_required(login_url='main_site:login', redirect_field_name='next')
def logoutAA(request):
    logout(request)
    return redirect(reverse('main_site:home'))

projeto_integrador/main_site/views/projeto_views.py
from django.contrib.staticfiles import finders
from django.shortcuts import render
from main_site.forms.editor_form import EditorForm
from main_site.models import Projeto
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse
import os

def excluir_projeto(request, pk):
    projeto_obj = get_object_or_404(Projeto, pk=pk)
    if not projeto_obj.autor == request.user: Http404
    projeto_obj.delete()
    return redirect(reverse("main_site:home"))

def visualizar_projeto(request, pk,*args, **kwargs):
    projeto_obj = get_object_or_404(Projeto, pk=pk)
    template_path = 'main_site/view.html'
   
    context = {
        "projeto": 
            {
                "id": projeto_obj.idprojeto,
                "titulo": projeto_obj.titulo,
                "descricao": projeto_obj.descricao,
                "imagem": projeto_obj.imagem
            }
            
    }
    if projeto_obj.autor == request.user:
        context["projeto"]["autor"] = True
    return render(request, template_path, context)

def editar_projeto(request, pk, *args, **kwargs):
    projeto_obj = get_object_or_404(Projeto, pk=pk)
    if  not projeto_obj.autor == request.user: Http404
    edit_form_data = request.session.get('edit_form_data', None)
    template_path = 'main_site/editor.html'
    projeto_obj.imagem = ""
    form = EditorForm(instance=projeto_obj)
    context = {
        "form": form,
        "projeto": 
            {
                "idprojeto": projeto_obj.idprojeto,
                "titulo": projeto_obj.titulo,
                "descricao": projeto_obj.descricao,
            },
        # "form_action": reverse('main_site:performar_editar_projeto')
    }
    return render(request, template_path, context)

def criar_projeto(request, *args, **kwargs):
    template_path = 'main_site/editor.html'
    form = EditorForm(request.session.get('register_form_data', None))
    context = {
        "form": form,
        "criacao": True,
    }
    return render(request, template_path, context)

def performar_criar_projeto(request):

    if not request.POST: Http404
    POST = request.POST
    request.session['register_form_data'] = POST
    form = EditorForm(POST, request.FILES)
    if form.is_valid():
        imagem_enviada = request.FILES.get('imagem', None)
        instance = Projeto(
            autor=request.user,
            titulo=form.cleaned_data['titulo'],
            descricao=form.cleaned_data['descricao'],
            imagem=imagem_enviada
        )
        instance.save()
        del(request.session['register_form_data'])
        return redirect(reverse('main_site:visualizar_projeto', args=[instance.idprojeto]))
    else:
        return redirect(reverse('main_site:criar_projeto'))


def performar_editar_projeto(request, pk, *args, **kwargs):
    projeto_obj = get_object_or_404(Projeto, pk=pk)
    if not projeto_obj.autor == request.user: Http404
    if not request.POST: Http404
    
    POST = request.POST
    request.session['register_form_data'] = POST
    form = EditorForm(request.POST, request.FILES, instance=projeto_obj)
    if form.is_valid():
        imagem = request.FILES.get('imagem', None)
        projeto_obj.titulo = form.cleaned_data['titulo']
        projeto_obj.descricao = form.cleaned_data['descricao']
        if imagem:
            projeto_obj.imagem = imagem

        projeto_obj.save()
        del(request.session['register_form_data'])
        return redirect(reverse('main_site:visualizar_projeto', args=[pk]))
    errors = form.errors
    print(errors)
    return redirect(reverse('main_site:visualizar_projeto', args=[pk]))

projeto_integrador/main_site/templates/main_site/editor.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Projeto</title>
    <link rel="stylesheet" href="{% static 'main_site/css/editor.css' %}">
</head>
<body>
    <nav>
        <button id="voltar_button" class="{{projeto.idprojeto}}">Voltar</button>
    </nav>
    <main> 
        <div class="container">
            {% if criacao %}

                <form action="/projeto/criar/performar/" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                        {{field}}
                    {% endfor %}

                    <button type="submit">Salvar</button>
                   
                </form>

            {% else %}
                <form action="/projeto/editar/performar/{{projeto.idprojeto}}/" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                        {{field}}
                    {% endfor %}

                    <button type="submit">Salvar</button>
                </form>
                <button id="excluir_button" type="button" style="margin-top: 8px; background-color: rgb(248, 153, 153);">Excluir</button>
            {% endif %}
        </div>
    </main>
</body>
</html>
<script>
    const voltar_button = document.getElementById('voltar_button')
    const excluir_button = document.getElementById('excluir_button')
    if (voltar_button) voltar_button.addEventListener('click', voltar_button_function)
    const id = voltar_button.classList[0]
    function voltar_button_function() {
        const a = document.createElement('a')
        let b;
        if (!id){
            b = `/`
        } else {
            b =  `/projeto/${id}/`
        }
        a.href = b
        a.click();
    }
    if(excluir_button) excluir_button.addEventListener("click", excluir_button_function)
    function excluir_button_function() {
        const a = document.createElement('a')
        let b;
        if (!id){
            b = `/`
        } else {
            b =  `/projeto/excluir/${id}/`
        }
        a.href = b
        a.click();
    }
</script>

projeto_integrador/main_site/templates/main_site/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página inicial</title>
    <link rel="stylesheet" href="{%static '/main_site/css/home.css'%}">
</head>
<body>
        <nav>
            <header>
                {% if usuario_logado %}
                    <button id="logout_button">Logout</button>  
                    <button id="criar_button">Criar projeto</button>
                {% else %}
                    <button id="login_button">Login</button>    
                    <button id="register_button">Registre-se</button>
                {% endif %}    
            
                <h2><b>Gerenciador de Projetos Coletivo</b></h2>
            </header>
        </nav>
        <main>
            <div class="container">
                {% for item in projetos %}
                    <div class="card" id="{{item.idprojeto}}">
                        <h3 class="clicavel bold-text" id="{{item.idprojeto}}">{{item.titulo}}</h3>
                        <img  class="clicavel" id="{{item.idprojeto}}" src="{{item.imagem}}" alt="">
                        <h4  class="clicavel adding" id="{{item.idprojeto}}">{{item.descricao}}</h3>
                    </div>
                {% endfor %}
            </div>
        </main>
</body>
</html>
<script>
    //Componentes dos botões
    const elementos = document.getElementsByClassName('clicavel') 
    const logout_buttom = document.getElementById('logout_button')
    const login_buttom = document.getElementById('login_button')
    const criar_buttom = document.getElementById('criar_button')
    const register_button = document.getElementById('register_button')
    //Função de redirecionar para o login
    if (logout_buttom) logout_buttom.addEventListener('click', logout_function)
    function logout_function() {
        const a = document.createElement('a')
        a.href = "{% url 'main_site:logout' %}"
        a.click()
    }
    //Função de redirecionar para o register
    if (register_button) register_button.addEventListener("click", register_redirect_function)
    function register_redirect_function() {
        const a = document.createElement('a')
        a.href = "{% url 'main_site:register' %}"
        a.click()
    }
    //Função de redirecionar para o logout
    if (login_buttom) login_buttom.addEventListener('click', login_redirect_function)
    function login_redirect_function() {
        const a = document.createElement('a')
        a.href = "{% url 'main_site:login' %}"
        a.click()
    }
    if (criar_buttom) criar_buttom.addEventListener("click", criar_function)
    function criar_function() {
        const a = document.createElement('a')
        a.href = "{% url 'main_site:criar_projeto' %}"
        a.click()
    }
    //Adicionar redirecionamento para cada card
    for (const elemento of elementos) {
        if(elemento.classList.contains('clicavel')) {
            elemento.addEventListener('click', handleClick)
        }
    }





    //Função de redirecionar para infos do card.
    function handleClick(evento) {
        console.log(evento.target.id)
        const a = document.createElement('a')
        const b = `/projeto/${evento.target.id}/`
        a.href =b
        a.click()
    }

</script>

projeto_integrador/main_site/templates/main_site/login.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if login %}
        <title>Login</title>
    {% else %}
        <title>Registrar</title>
    {% endif %}
    <link rel="stylesheet" href="{%static '/main_site/css/login.css'%}"><link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container">
        {% if login %}

            <h1>Inicie a sessão</h1>

            <form action="/auth/" method="post">
                {% csrf_token %}
                {% for field in form %}

                    {{field}}

                {% endfor %}
                <button type="submit">Entrar</button>
            </form>

        {% else %}

            <h1>Registre-se</h1>

            <form action="/perform_register/" method="post">
                {% csrf_token %}
                {% for field in form %}

                    {{field}}
                    {{field.errors}}
                {% endfor %}
                <button type="submit">Registrar</button>
                <button id="button_voltar">Voltar</button>
            </form>

        {% endif %}
        
    </div>
</body>
</html>
<script>

    const button_voltar = document.getElementById('button_voltar')
    if (button_voltar) button_voltar.addEventListener("click", () => {
        const a = document.createElement('a')
        a.href= "{% url 'main_site:home' %}"
        a.click()
    })

</script>

projeto_integrador/main_site/templates/main_site/view.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualizar projeto</title>
    <link rel="stylesheet" href="{% static 'main_site/css/view.css' %}">
</head>
<body>
    <nav>
        <button id="voltar_button">Voltar</button>
    </nav>
    <main>
        <div class="container">
            <h2>{{projeto.titulo}}</h2>
            <textarea name="" id="" cols="60" rows="20" disabled style="background-color: white;">{{projeto.descricao}}</textarea>
            {% if projeto.autor %}
                <button id="editar_button" class="{{projeto.id}}" style="margin-top: 12px;">Editar</button>
            {% endif %}
        </div>
        <img src="{{projeto.imagem.url}}" alt=""/>
    </main>
</body>
</html>
<script>

    const voltar_button = document.getElementById('voltar_button')
    if (voltar_button) voltar_button.addEventListener("click", voltar_button_function)
    function voltar_button_function() {
        const a = document.createElement('a')
        a.href = '{% url "main_site:home" %}'
        a.click();
    }

    const editar_button = document.getElementById('editar_button')
    if (editar_button) editar_button.addEventListener('click', editar_button_function)
    const id = editar_button.classList[0]
    function editar_button_function() {
        const a = document.createElement('a')
        const b =  `/projeto/editar/${id}/`
        a.href = b
        a.click();
    }

</script>